[window]
opacity = 0.9
startup_mode = "Maximized"

[font]
normal = { family = "FiraCode Nerd Font Mono", style = "Regular" }
size = 12

[terminal]
# Launch into tmux, or attach to existing session
shell = { program = "wsl.exe", args = ["~"] }
